import type { Quat } from "../math/types";
import type { RigDefinition, RigJointDefinition } from "./types";

const identity: Quat = [0, 0, 0, 1];

const joints = [
  {
    id: "HumanoidRootPart",
    parentId: null,
    displayName: "Root",
    side: "center",
    mirrorId: "HumanoidRootPart",
    editableRotation: true,
    editablePosition: true,
    bindPosition: [0, 0, 0],
    bindRotation: identity,
    visual: { shape: "box", size: [2, 2, 1], offset: [0, -0.5, 0] },
  },
  {
    id: "LowerTorso",
    parentId: "HumanoidRootPart",
    displayName: "Lower Torso",
    side: "center",
    mirrorId: "LowerTorso",
    editableRotation: true,
    editablePosition: false,
    bindPosition: [0, 0.6, 0],
    bindRotation: identity,
    visual: { shape: "box", size: [1.4, 1.2, 0.8], offset: [0, 0, 0] },
  },
  {
    id: "UpperTorso",
    parentId: "LowerTorso",
    displayName: "Upper Torso",
    side: "center",
    mirrorId: "UpperTorso",
    editableRotation: true,
    editablePosition: false,
    bindPosition: [0, 0.6, 0],
    bindRotation: identity,
    visual: { shape: "box", size: [1.8, 1.2, 0.9], offset: [0, 0, 0] },
  },
  {
    id: "Head",
    parentId: "UpperTorso",
    displayName: "Head",
    side: "center",
    mirrorId: "Head",
    editableRotation: true,
    editablePosition: false,
    bindPosition: [0, 0.75, 0],
    bindRotation: identity,
    visual: { shape: "box", size: [1.2, 1.2, 1.2], offset: [0, 0, 0] },
  },
  {
    id: "LeftUpperArm",
    parentId: "UpperTorso",
    displayName: "Left Upper Arm",
    side: "left",
    mirrorId: "RightUpperArm",
    editableRotation: true,
    editablePosition: false,
    bindPosition: [-0.9, 0.35, 0],
    bindRotation: identity,
    visual: { shape: "box", size: [0.6, 0.9, 0.6], offset: [0, -0.45, 0] },
  },
  {
    id: "LeftLowerArm",
    parentId: "LeftUpperArm",
    displayName: "Left Lower Arm",
    side: "left",
    mirrorId: "RightLowerArm",
    editableRotation: true,
    editablePosition: false,
    bindPosition: [0, -0.45, 0],
    bindRotation: identity,
    visual: { shape: "box", size: [0.5, 0.9, 0.5], offset: [0, -0.45, 0] },
  },
  {
    id: "LeftHand",
    parentId: "LeftLowerArm",
    displayName: "Left Hand",
    side: "left",
    mirrorId: "RightHand",
    editableRotation: true,
    editablePosition: false,
    bindPosition: [0, -0.45, 0],
    bindRotation: identity,
    visual: { shape: "box", size: [0.45, 0.4, 0.45], offset: [0, -0.2, 0] },
  },
  {
    id: "RightUpperArm",
    parentId: "UpperTorso",
    displayName: "Right Upper Arm",
    side: "right",
    mirrorId: "LeftUpperArm",
    editableRotation: true,
    editablePosition: false,
    bindPosition: [0.9, 0.35, 0],
    bindRotation: identity,
    visual: { shape: "box", size: [0.6, 0.9, 0.6], offset: [0, -0.45, 0] },
  },
  {
    id: "RightLowerArm",
    parentId: "RightUpperArm",
    displayName: "Right Lower Arm",
    side: "right",
    mirrorId: "LeftLowerArm",
    editableRotation: true,
    editablePosition: false,
    bindPosition: [0, -0.45, 0],
    bindRotation: identity,
    visual: { shape: "box", size: [0.5, 0.9, 0.5], offset: [0, -0.45, 0] },
  },
  {
    id: "RightHand",
    parentId: "RightLowerArm",
    displayName: "Right Hand",
    side: "right",
    mirrorId: "LeftHand",
    editableRotation: true,
    editablePosition: false,
    bindPosition: [0, -0.45, 0],
    bindRotation: identity,
    visual: { shape: "box", size: [0.45, 0.4, 0.45], offset: [0, -0.2, 0] },
  },
  {
    id: "LeftUpperLeg",
    parentId: "LowerTorso",
    displayName: "Left Upper Leg",
    side: "left",
    mirrorId: "RightUpperLeg",
    editableRotation: true,
    editablePosition: false,
    bindPosition: [-0.35, -0.6, 0],
    bindRotation: identity,
    visual: { shape: "box", size: [0.65, 1, 0.7], offset: [0, -0.5, 0] },
  },
  {
    id: "LeftLowerLeg",
    parentId: "LeftUpperLeg",
    displayName: "Left Lower Leg",
    side: "left",
    mirrorId: "RightLowerLeg",
    editableRotation: true,
    editablePosition: false,
    bindPosition: [0, -0.5, 0],
    bindRotation: identity,
    visual: { shape: "box", size: [0.55, 1, 0.6], offset: [0, -0.5, 0] },
  },
  {
    id: "LeftFoot",
    parentId: "LeftLowerLeg",
    displayName: "Left Foot",
    side: "left",
    mirrorId: "RightFoot",
    editableRotation: true,
    editablePosition: false,
    bindPosition: [0, -0.5, -0.1],
    bindRotation: identity,
    visual: { shape: "box", size: [0.55, 0.35, 0.9], offset: [0, -0.175, -0.15] },
  },
  {
    id: "RightUpperLeg",
    parentId: "LowerTorso",
    displayName: "Right Upper Leg",
    side: "right",
    mirrorId: "LeftUpperLeg",
    editableRotation: true,
    editablePosition: false,
    bindPosition: [0.35, -0.6, 0],
    bindRotation: identity,
    visual: { shape: "box", size: [0.65, 1, 0.7], offset: [0, -0.5, 0] },
  },
  {
    id: "RightLowerLeg",
    parentId: "RightUpperLeg",
    displayName: "Right Lower Leg",
    side: "right",
    mirrorId: "LeftLowerLeg",
    editableRotation: true,
    editablePosition: false,
    bindPosition: [0, -0.5, 0],
    bindRotation: identity,
    visual: { shape: "box", size: [0.55, 1, 0.6], offset: [0, -0.5, 0] },
  },
  {
    id: "RightFoot",
    parentId: "RightLowerLeg",
    displayName: "Right Foot",
    side: "right",
    mirrorId: "LeftFoot",
    editableRotation: true,
    editablePosition: false,
    bindPosition: [0, -0.5, -0.1],
    bindRotation: identity,
    visual: { shape: "box", size: [0.55, 0.35, 0.9], offset: [0, -0.175, -0.15] },
  },
] as const satisfies readonly RigJointDefinition[];

export const R15_RIG: RigDefinition = {
  id: "R15",
  displayName: "R15 Block",
  rootId: "HumanoidRootPart",
  joints,
};
