import type { Quat } from "../math/types";
import type { RigDefinition, RigJointDefinition } from "./types";

const identity: Quat = [0, 0, 0, 1];

const joints = [
  {
    id: "HumanoidRootPart",
    parentId: null,
    displayName: "Root",
    side: "center",
    mirrorId: "HumanoidRootPart",
    editableRotation: true,
    editablePosition: true,
    bindPosition: [0, 0, 0],
    bindRotation: identity,
    visual: { shape: "box", size: [2, 2, 1], offset: [0, -0.5, 0] },
  },
  {
    id: "Torso",
    parentId: "HumanoidRootPart",
    displayName: "Torso",
    side: "center",
    mirrorId: "Torso",
    editableRotation: true,
    editablePosition: false,
    bindPosition: [0, 1, 0],
    bindRotation: identity,
    visual: { shape: "box", size: [2, 2, 1], offset: [0, 0, 0] },
  },
  {
    id: "Head",
    parentId: "Torso",
    displayName: "Head",
    side: "center",
    mirrorId: "Head",
    editableRotation: true,
    editablePosition: false,
    bindPosition: [0, 1.5, 0],
    bindRotation: identity,
    visual: { shape: "box", size: [2, 1, 1], offset: [0, 0, 0] },
  },
  {
    id: "Left Arm",
    parentId: "Torso",
    displayName: "Left Arm",
    side: "left",
    mirrorId: "Right Arm",
    editableRotation: true,
    editablePosition: false,
    bindPosition: [-1.5, 0, 0],
    bindRotation: identity,
    visual: { shape: "box", size: [1, 2, 1], offset: [0, -0.5, 0] },
  },
  {
    id: "Right Arm",
    parentId: "Torso",
    displayName: "Right Arm",
    side: "right",
    mirrorId: "Left Arm",
    editableRotation: true,
    editablePosition: false,
    bindPosition: [1.5, 0, 0],
    bindRotation: identity,
    visual: { shape: "box", size: [1, 2, 1], offset: [0, -0.5, 0] },
  },
  {
    id: "Left Leg",
    parentId: "Torso",
    displayName: "Left Leg",
    side: "left",
    mirrorId: "Right Leg",
    editableRotation: true,
    editablePosition: false,
    bindPosition: [-0.5, -2, 0],
    bindRotation: identity,
    visual: { shape: "box", size: [1, 2, 1], offset: [0, -0.5, 0] },
  },
  {
    id: "Right Leg",
    parentId: "Torso",
    displayName: "Right Leg",
    side: "right",
    mirrorId: "Left Leg",
    editableRotation: true,
    editablePosition: false,
    bindPosition: [0.5, -2, 0],
    bindRotation: identity,
    visual: { shape: "box", size: [1, 2, 1], offset: [0, -0.5, 0] },
  },
] as const satisfies readonly RigJointDefinition[];

export const R6_RIG: RigDefinition = {
  id: "R6",
  displayName: "R6",
  rootId: "HumanoidRootPart",
  joints,
};
